let myjokes = [
  {
    category: "Programming",
    type: "single",
    joke: 'A SQL statement walks into a bar and sees two tables.\nIt approaches, and asks "may I join you?"',
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 5,
    safe: true,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: '"Honey, go to the store and buy some eggs."\n"OK."\n"Oh and while you\'re there, get some milk."\nHe never returned.',
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 18,
    safe: true,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: "Knock knock.\nWho's there?\nRecursion.\nRecursion who?\nKnock knock.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 180,
    safe: true,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: 'Four engineers get into a car. The car won\'t start.\nThe Mechanical engineer says "It\'s a broken starter".\nThe Electrical engineer says "Dead battery".\nThe Chemical engineer says "Impurities in the gasoline".\nThe IT engineer says "Hey guys, I have an idea: How about we all get out of the car and get back in".',
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 132,
    safe: true,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: "ASCII silly question, get a silly ANSI.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 25,
    safe: true,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: "How do you tell HTML from HTML5?\n- Try it out in Internet Explorer\n- Did it work?\n- No?\n- It's HTML5.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 43,
    safe: true,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: 'A man is smoking a cigarette and blowing smoke rings into the air. His girlfriend becomes irritated with the smoke and says "Can\'t you see the warning on the cigarette pack? Smoking is hazardous to your health!" to which the man replies, "I am a programmer.  We don\'t worry about warnings; we only worry about errors."',
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 38,
    safe: true,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: "Hey Girl,\nRoses are #ff0000,\nViolets are #0000ff,\nI use hex codes,\nBut I'd use RGB for you.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 41,
    safe: true,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: "Have a great weekend!\nI hope your code behaves the same on Monday as it did on Friday.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 44,
    safe: true,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: 'Two SQL tables sit at the bar. A query approaches and asks "Can I join you?"',
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 221,
    safe: true,
    lang: "en",
  },
  {
    category: "Misc",
    type: "single",
    joke: "Yo mama is so old, she knew Burger King while he was still a prince.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    safe: true,
    id: 306,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: "The six stages of debugging:\n1. That can't happen.\n2. That doesn't happen on my machine.\n3. That shouldn't happen.\n4. Why does that happen?\n5. Oh, I see.\n6. How did that ever work?",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 123,
    safe: true,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: "ASCII silly question, get a silly ANSI.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 25,
    safe: true,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: 'Four engineers get into a car. The car won\'t start.\nThe Mechanical engineer says "It\'s a broken starter".\nThe Electrical engineer says "Dead battery".\nThe Chemical engineer says "Impurities in the gasoline".\nThe IT engineer says "Hey guys, I have an idea: How about we all get out of the car and get back in".',
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 132,
    safe: true,
    lang: "en",
  },
  {
    category: "Misc",
    type: "single",
    joke: "I went to the zoo the other day. There was only a dog in it – it was a shihtzu.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: true,
    },
    safe: false,
    id: 307,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: "Debugging is like being the detective in a crime movie where you're also the murderer at the same time.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 42,
    safe: true,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: "Being a self-taught developer is almost the same as being a cut neck chicken because you have no sense of direction in the beginning.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 184,
    safe: false,
    lang: "en",
  },
  {
    category: "Misc",
    type: "single",
    joke: "I visited my friend at his new house. He told me to make myself at home. So I threw him out. I hate having visitors.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    safe: true,
    id: 304,
    lang: "en",
  },
  {
    category: "Pun",
    type: "single",
    joke: "I'm reading a book about anti-gravity. It's impossible to put down!",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 126,
    safe: true,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: "I'd tell you a joke about NAT but I would have to translate.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    safe: true,
    id: 319,
    lang: "en",
  },
];

let index = Math.floor(Math.random()*myjokes.length-1)
joke.innerHTML = myjokes[index].joke


